# -*- coding: utf-8 -*-
"""GOMO_phone_number_scoring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HwjXNhckdOiGmpugFN0vjBrrOuUNZk8I
"""

import requests

### Add your favorites numbers
FAVORITE = ["21", "97", "05"]


mylist={}
for i in range(1, 20):
    url = "https://buy.gomo.sg/api/hybrid/v1/numbers/" + str(i)
    response = requests.get(url)
    print(str(i) + " => " + url)

    for el in response.json()["content"]:
        mylist[el["id"]] = {
            "number": el["number"],
            "id": el["id"]
        }


"""Divide the phone number"""


for i in mylist:
    mylist[i]["splitNumber"] = [mylist[i]["number"][0:2], mylist[i]["number"][2:4], mylist[i]["number"][4:6], mylist[i]["number"][6:8]]
  
    

"""Detect the interesting numbers"""

from enum import Enum


class D(Enum):
    M11 = 1 # 22, 55...
    M10 = 2 # 10, 40...
    SPECIAL = 3 # Special numers: 21, 97, 05...
    SAME_N = 4 # 57, 12, 57
#     SUITE = 4 # Suite: 34,35...


def detection(phoneArr):
    detectionArr = []
    detectionArr.append(M11Detect(phoneArr))
    detectionArr.append(M10Detect(phoneArr))
    detectionArr.append(SpecialDetect(phoneArr))
    detectionArr.append(SameDetect(phoneArr))
    
    return detectionArr
    
def M11Detect(phoneArr):
    result={"d": D.M11}
    indexes=[]
    for i in range(len(phoneArr)):
        if (int(phoneArr[i])%11 == 0): indexes.append(i)
    result["i"]=indexes
    return result

def M10Detect(phoneArr):
    result={"d": D.M10}
    indexes=[]
    for i in range(len(phoneArr)):
        if (int(phoneArr[i])%10 == 0): indexes.append(i)
    result["i"]=indexes
    return result


def SpecialDetect(phoneArr):
    result={"d": D.SPECIAL}
    indexes=[]
    specialNum = FAVORITE
    for i in range(len(phoneArr)):
        if phoneArr[i] in specialNum: indexes.append(i)
    result["i"]=indexes
    return result


def SameDetect(phoneArr):
    result={"d": D.SAME_N}
    recc={}
    reccResult={}
    for i in range(len(phoneArr)): recc[phoneArr[i]] = []
    for i in range(len(phoneArr)):
        recc[phoneArr[i]].append(i)
    for i in recc:
        if len(recc[i]) > 1:
            reccResult[i] = recc[i]  
    result["i"]=reccResult
    return result
    


for i in mylist:
    mylist[i]["detection"] = detection(mylist[i]["splitNumber"])



"""Give a quick score"""

for i in mylist:
    score=0
    for d in mylist[i]["detection"]:

        if (d["d"] == D.M11):
            score += len(d["i"]) * 2
        
        if (d["d"] == D.M10):
            score += len(d["i"]) * 1
        
        if (d["d"] == D.SPECIAL):
            score += len(d["i"]) * 1
        
        if (d["d"] == D.SAME_N): # 'i': {'42': [2, 3]}}
            for key in d["i"]:
                if len(d["i"]) >= 3: score += 10
                else: score += 6
        
    mylist[i]["score"] = score



"""Sort"""

newlist = sorted(mylist.values(), key=lambda k: k['score'], reverse=True)

for num in newlist:
    if num["score"] >= 7:
        print(str(num["number"]) + " => " + str(num["score"]))
        # print("id: " + str(num["id"]))
        # for d in num["detection"]:
        #   print(d)
        # print()

print("..." + str(len(newlist)) + " results")